CREATE TABLE WebInfo
(
    webId BIGINT(20) NOT NULL,
    webName VARCHAR(50) NOT NULL,
    domainName VARCHAR(255) NOT NULL,
    ipAdress VARCHAR(50),
    departId VARCHAR(20) NOT NULL,
    departIndex VARCHAR(25) NOT NULL,
    department VARCHAR(20),
    charge VARCHAR(20),
    chargeTel VARCHAR(20),
    administor VARCHAR(20),
    houseTel VARCHAR(20),
    mobilePhone VARCHAR(20),
    email VARCHAR(255),
    qq VARCHAR(20),
    category VARCHAR(20),
    classification VARCHAR(30),
    indexOfTeach VARCHAR(20),
    priority VARCHAR(20),
    statue VARCHAR(20),
    closeTime VARCHAR(20),
    closeReason VARCHAR(255),
    openTime VARCHAR(20),
    remark VARCHAR(255),
    recordNum VARCHAR(255),
    inRecord VARCHAR(5),
    recordDate VARCHAR(20),
    isOpen VARCHAR(20),
    webApplyNum VARCHAR(20),
    isDisconnect VARCHAR(20),
    remark2 VARCHAR(255),
    exploreRange VARCHAR(50),
    isSchoolDomain VARCHAR(5),
    isUseDatabase VARCHAR(5),
    webStatue VARCHAR(5)
);
CREATE UNIQUE INDEX WebInfo_webId_uindex ON WebInfo (webId);